nome= input("Digite o nome do cliente: ")
diavenc= input("Digite o dia de vencimento: ")
mesvenc= input("Digite o mês de vencimento: ")
vlrfatura= input("Digite o valor da fatura: ")
print ("Olá,",nome) 
print ("A sua fatura com vencimento em",diavenc,"de",mesvenc,"no valor de R$",vlrfatura,"está fechada.")
